version: '3.8'
services:
  backend:
    image: tutor-inteligente-backend:latest
    container_name: tutor-backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend/database:/app/database
      - ./backend/uploads:/app/uploads
    env_file:
      - .env

  frontend:
    image: tutor-inteligente-frontend:latest
    container_name: tutor-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
